"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Nav } from "@/components/Nav";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/components/Footer";
///export const metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <NextUIProvider>
          <Nav />
          {children}
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
